# Generated by Django 4.2.7 on 2024-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание плана благоустройства')),
                ('image', models.ImageField(default=None, null=True, upload_to='plans/images', verbose_name='Изображене плана благоустройства')),
                ('stage', models.CharField(choices=[('PLANNING', 'Планирование'), ('DESIGNING', 'Проектирование'), ('REALISATION', 'Реализация')], default='PLANNING', max_length=11, verbose_name='Стадия')),
                ('pdf_file', models.FileField(default=None, upload_to='plans/pdf_files', verbose_name='Файл с подробным описанием плана благоустройства')),
            ],
        ),
    ]
