# Generated by Django 4.2.7 on 2024-01-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='pdf_file',
            field=models.FileField(default=None, null=True, upload_to='plans/pdf_files', verbose_name='Файл с подробным описанием плана благоустройства'),
        ),
    ]
