# Generated by Django 4.2.7 on 2024-02-09 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plan_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст сообщения')),
                ('image', models.ImageField(default=None, null=True, upload_to='urgent_messages/images', verbose_name='Изображение к сообщению')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
