# Generated by Django 4.2.7 on 2024-02-15 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodDeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('roads', 'Дороги'), ('lighting', 'Уличное освещение'), ('improvment', 'Благоустройство'), ('property', 'Содержание имущества'), ('other', 'Иное')], max_length=10, verbose_name='Тема обращения')),
                ('descriptiion', models.TextField(verbose_name='Текст обращения')),
                ('stage', models.CharField(choices=[('consideration', 'На рассмотрении'), ('executed', 'Выполнено'), ('not_executed', 'Не выполнено'), ('in_progress', 'В процессе выполнения')], default='consideration', max_length=13, verbose_name='Статус исполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_deeds', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель обращения')),
            ],
        ),
    ]
