# Generated by Django 4.2.7 on 2024-02-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_deeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gooddeed',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
