# Generated by Django 4.2.7 on 2023-11-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_aderss_customuser_patronymic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='patronymic',
            new_name='middle_name',
        ),
    ]
