# Generated by Django 4.2.7 on 2023-11-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_patronymic_customuser_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='aderss',
            new_name='address',
        ),
    ]
